# Site settings
title: Dimension
email: roberto@reale.info
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dimension-jekyll-theme.reale.info" # the base hostname & protocol for your site
author: Roberto Reale
street_address:
city:
state:
zip_code:
country:
phone:

icon: # Font Awesome class for your site's icon
formspree_id: myylkdnk # formspree.io

# Social settings
facebook_url:
github_url: https://github.com/reale
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
style: compressed
